# Generated by Django 4.2.7 on 2024-07-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstate',
            name='state',
        ),
        migrations.RemoveField(
            model_name='userstate',
            name='user_profile',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='date',
            new_name='race_date',
        ),
        migrations.RenameField(
            model_name='race',
            old_name='notes',
            new_name='race_notes',
        ),
        migrations.AddField(
            model_name='race',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='state',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='state_flags/'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='UserState',
        ),
    ]
