# Generated by Django 4.2.7 on 2024-07-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_remove_userstate_state_remove_userstate_user_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='flag_image',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
