# Generated by Django 4.2.7 on 2024-07-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_remove_race_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='race_image',
            field=models.ImageField(blank=True, null=True, upload_to='race_images/'),
        ),
    ]
