# Generated by Django 4.2.7 on 2024-07-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_rename_race_image_race_race_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_date',
            field=models.DateField(null=True),
        ),
    ]
