# Generated by Django 4.2.7 on 2024-07-16 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_alter_race_race_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255)),
                ('street2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('country_code', models.CharField(default='US', max_length=2)),
                ('zipcode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExternalRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('last_date', models.DateField(blank=True, null=True)),
                ('last_end_date', models.DateField(blank=True, null=True)),
                ('next_date', models.DateField()),
                ('next_end_date', models.DateField()),
                ('is_draft_race', models.CharField(max_length=1)),
                ('is_private_race', models.CharField(max_length=1)),
                ('is_registration_open', models.CharField(max_length=1)),
                ('created', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('description', models.TextField()),
                ('url', models.URLField()),
                ('external_race_url', models.URLField(blank=True, null=True)),
                ('external_results_url', models.URLField(blank=True, null=True)),
                ('fb_page_id', models.CharField(blank=True, max_length=255, null=True)),
                ('fb_event_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(max_length=255)),
                ('logo_url', models.URLField()),
                ('real_time_notifications_enabled', models.CharField(max_length=1)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.address')),
            ],
        ),
    ]
