# Generated by Django 4.2.7 on 2024-07-19 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_wishlistitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
