# Generated by Django 4.2.7 on 2024-07-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_state_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
