# Generated by Django 4.2.7 on 2024-07-23 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_race_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='logo_url',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='race_date',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='race_id',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='race_name',
        ),
        migrations.RemoveField(
            model_name='wishlistitem',
            name='race_url',
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='external_race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='races.externalrace'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='country_code',
            field=models.CharField(blank=True, default='US', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='races.address'),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_draft_race',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_private_race',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_registration_open',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='last_modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='next_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='real_time_notifications_enabled',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
