# Generated by Django 4.2.7 on 2024-07-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_remove_wishlistitem_logo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrace',
            name='is_draft_race',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_private_race',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_registration_open',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='real_time_notifications_enabled',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
