# Generated by Django 4.2.7 on 2024-07-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_alter_externalrace_is_draft_race_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalrace',
            name='is_draft_race',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_private_race',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='is_registration_open',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='externalrace',
            name='real_time_notifications_enabled',
            field=models.CharField(max_length=5),
        ),
    ]
